---
name: CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal:1.18.0

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Install dev packages
        run: apt-get update && apt-get install -y build-essential automake autoconf libtool

      - name: Build vendored libucl
        run: make libucl

      - name: Run tests
        run: make spec
